"""create news source table

Revision ID: 84cc05974f21
Revises: 
Create Date: 2025-04-22 14:24:07.233949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84cc05974f21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_source_country'), 'news_source', ['country'], unique=False)
    op.create_index(op.f('ix_news_source_country_code'), 'news_source', ['country_code'], unique=True)
    op.create_index(op.f('ix_news_source_id'), 'news_source', ['id'], unique=False)
    op.create_index(op.f('ix_news_source_name'), 'news_source', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_source_name'), table_name='news_source')
    op.drop_index(op.f('ix_news_source_id'), table_name='news_source')
    op.drop_index(op.f('ix_news_source_country_code'), table_name='news_source')
    op.drop_index(op.f('ix_news_source_country'), table_name='news_source')
    op.drop_table('news_source')
    # ### end Alembic commands ###
